name: Run Halaqa Agent Monthly
on:
  schedule:
    - cron:  '0 13 1 * *'   # 09:00 Toronto on the 1st of every month
  workflow_dispatch:

jobs:
  halaqa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: '3.11' }
    - name: Install deps
      run: |
        python -m pip install -r requirements.txt
    - name: Decrypt secrets & run
      env: 
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SA_JSON }}
        SHEET_ID:                    ${{ secrets.SHEET_ID }}
        SHEET_RANGE:                 Commitments!A:B
        WA_GATEWAY_URL:              ${{ secrets.WA_GATEWAY_URL }}
      run: python run_halaqa.py 